name: samples

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
    - uses: actions/checkout@v4
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Test
      run: dotnet test sample/Yapoml.Playwright.Sample/Yapoml.Playwright.Sample.csproj
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
