name: samples

on:
  push:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 10.0.x
    - name: Authenticate GitHub Packages
      run: dotnet nuget update source "GitHub Yapoml" --username yapoml --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Test
      run: dotnet test sample/Yapoml.Playwright.Sample/Yapoml.Playwright.Sample.csproj
